---
namespace: craig_br
name: portal_experience_demo
version: 1.0.0
readme: README.md
authors:
  - Craig Brandt

dependencies:
  - "redhat.rhel_system_roles": ">=1.23.0"
description: A Demo Ansible Experience
license_file: LICENSE
tags: []

repository: https://www.github.com/craig-br/portal_experience_demo
documentation: https://www.github.com/craig-br/portal_experience_demo
homepage: https://www.github.com/craig-br/portal_experience_demo
