---
name: configure-windows
description: ''
spec:
  - question_name: "Windows Survey"
    question_description: "Provide the list of NTP servers to be configured, e.g., '0.rhel.pool.ntp.org', '1.rhel.pool.ntp.org'."
    required: true
    variable: "ntp_servers"
    type: "text"
    default: "0.rhel.pool.ntp.org, 1.rhel.pool.ntp.org"
